# Generated by Django 2.0.9 on 2018-10-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20181021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Bus', verbose_name='bus'),
        ),
    ]
