# Generated by Django 2.0.9 on 2018-10-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_trip_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.Bus', verbose_name='bus'),
            preserve_default=False,
        ),
    ]
